Repository Effect-TS/effect, pull requests merged in 2024-10, with the labels that each got.

#3753 Enhanced Error Reporting for Discriminated Union Tuple Schemas, close…
  .changeset/cyan-pillows-listen.md
  packages/schema/src/ParseResult.ts
  packages/schema/test/ParseResult.test.ts
  packages/schema/test/Schema/Union/Union.test.ts
Labels: schema

#3748 platform: add documentation on Scope requirement for HTTP requests
  packages/platform/README.md
Labels: documentation

#3761 Allow Schema.Either to support Never without type errors, closes #3755
  .changeset/wet-balloons-swim.md
  packages/schema/dtslint/Schema.ts
  packages/schema/src/Schema.ts
Labels: schema

#2725 add TSubscriptionRef
  .changeset/cold-cougars-pretend.md
  .changeset/shiny-squids-sell.md
  packages/effect/src/Stream.ts
  packages/effect/src/TPubSub.ts
  packages/effect/src/TQueue.ts
  packages/effect/src/TRef.ts
  packages/effect/src/TSubscriptionRef.ts
  packages/effect/src/index.ts
  packages/effect/src/internal/stm/core.ts
  packages/effect/src/internal/stm/tPubSub.ts
  packages/effect/src/internal/stm/tQueue.ts
  packages/effect/src/internal/stm/tRef.ts
  packages/effect/src/internal/stm/tSubscriptionRef.ts
  packages/effect/src/internal/stream.ts
  packages/effect/test/TSubscriptionRef.test.ts
Labels: next-minor

#3795 Vitest README: add Logging section
  packages/vitest/README.md
Labels: documentation

#3797 Add JSDoc comments for effect creation and execution APIs
  packages/effect/src/Effect.ts
  packages/effect/src/internal/core-effect.ts
  packages/effect/src/internal/core.ts
Labels: documentation

#3777 add Redactable to Inspectable module
  .changeset/unlucky-apples-warn.md
  packages/effect/src/Inspectable.ts
  packages/effect/src/internal/cause.ts
  packages/effect/src/internal/fiberRuntime.ts
  packages/effect/src/internal/logger.ts
  packages/effect/src/internal/redacted.ts
  packages/platform/src/Headers.ts
  packages/platform/test/Headers.test.ts
Labels: next-minor

#3773 Fix cli options repeated order
  .changeset/tasty-flies-call.md
  packages/cli/src/internal/options.ts
  packages/cli/test/Options.test.ts
Labels: cli

#3827 add JSDocs to GlobalValue module
  packages/effect/src/GlobalValue.ts
  packages/effect/src/index.ts
Labels: documentation

#3844 fix since tags
  packages/typeclass/src/data/Record.ts
Labels: typeclass

#3850 add "Zod enums" example/comparison, closes #3847
  schema/comparisons.md
Labels: documentation, schema
