Repository Effect-TS/effect, pull requests merged in 2025-05, with the labels that each got.

#4847 Schema: TaggedError no longer crashes when the `message` field is explicitly defined
  .changeset/tall-bobcats-rest.md
  packages/effect/src/Schema.ts
  packages/effect/test/Schema/Schema/Class/TaggedError.test.ts
Labels: bug, schema

#4705 Support multiple values in Function.apply
  .changeset/wise-adults-give.md
  packages/effect/dtslint/Function.tst.ts
  packages/effect/src/Function.ts
  packages/effect/test/Function.test.ts
Labels: next-minor

#4828 Add `Schedule.CurrentIterationMetadata` Reference
  .changeset/calm-geese-carry.md
  packages/effect/src/Schedule.ts
  packages/effect/src/internal/schedule.ts
  packages/effect/src/internal/stream.ts
  packages/effect/test/Effect/repeating.test.ts
  packages/effect/test/Effect/retrying.test.ts
  packages/effect/test/Effect/scheduling.test.ts
  packages/effect/test/Stream/repeating.test.ts
  packages/effect/test/Stream/retrying.test.ts
Labels: next-minor

#4911 feat: Function Parameters for Effect.Service
  .changeset/smooth-badgers-enter.md
  packages/effect/src/Effect.ts
  packages/effect/test/Effect/service.test.ts
Labels: next-minor

#4920 Add `round` and `sumAll` functions to `BigDecimal`
  .changeset/forty-friends-hammer.md
  packages/effect/src/BigDecimal.ts
  packages/effect/test/BigDecimal.test.ts
Labels: next-minor

#4943 relax `Schema.brand` constraint, closes #4942
  .changeset/solid-items-fly.md
  packages/effect/dtslint/Schema/Context.tst.ts
  packages/effect/src/Schema.ts
Labels: schema
